//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_source_tileset_H
#define METASPRITE_station_source_tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_source_tileset_TILE_ORIGIN 128
#define station_source_tileset_TILE_W 8
#define station_source_tileset_TILE_H 8
#define station_source_tileset_WIDTH 80
#define station_source_tileset_HEIGHT 80
#define station_source_tileset_TILE_COUNT 100
#define station_source_tileset_PALETTE_COUNT 5
#define station_source_tileset_COLORS_PER_PALETTE 4
#define station_source_tileset_TOTAL_COLORS 20
#define station_source_tileset_MAP_ATTRIBUTES station_source_tileset_map_attributes
#define station_source_tileset_MAP_ATTRIBUTES_WIDTH 10
#define station_source_tileset_MAP_ATTRIBUTES_HEIGHT 10
#define station_source_tileset_MAP_ATTRIBUTES_PACKED_WIDTH 10
#define station_source_tileset_MAP_ATTRIBUTES_PACKED_HEIGHT 10

BANKREF_EXTERN(station_source_tileset)

extern const palette_color_t station_source_tileset_palettes[20];
extern const uint8_t station_source_tileset_tiles[1600];

extern const unsigned char station_source_tileset_map[100];
extern const unsigned char station_source_tileset_map_attributes[100];

#endif
