//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_a_button_H
#define METASPRITE_a_button_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define a_button_TILE_ORIGIN 96
#define a_button_TILE_W 8
#define a_button_TILE_H 8
#define a_button_WIDTH 16
#define a_button_HEIGHT 16
#define a_button_TILE_COUNT 24
#define a_button_PIVOT_X 8
#define a_button_PIVOT_Y 8
#define a_button_PIVOT_W 16
#define a_button_PIVOT_H 16

BANKREF_EXTERN(a_button)

extern const uint8_t a_button_tiles[384];

extern const metasprite_t* const a_button_metasprites[12];

#endif
