//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_buttonframe_H
#define METASPRITE_buttonframe_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define buttonframe_TILE_ORIGIN 0
#define buttonframe_TILE_W 8
#define buttonframe_TILE_H 8
#define buttonframe_WIDTH 32
#define buttonframe_HEIGHT 8
#define buttonframe_TILE_COUNT 4

BANKREF_EXTERN(buttonframe)

extern const uint8_t buttonframe_tiles[64];


#endif
