//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_drill_h_H
#define METASPRITE_drill_h_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define drill_h_TILE_ORIGIN 9
#define drill_h_TILE_W 8
#define drill_h_TILE_H 8
#define drill_h_WIDTH 8
#define drill_h_HEIGHT 16
#define drill_h_TILE_COUNT 4
#define drill_h_PIVOT_X 4
#define drill_h_PIVOT_Y 8
#define drill_h_PIVOT_W 8
#define drill_h_PIVOT_H 16

BANKREF_EXTERN(drill_h)

extern const uint8_t drill_h_tiles[64];

extern const metasprite_t* const drill_h_metasprites[2];

#endif
