#pragma bank 1

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(drill_v)

const palette_color_t drill_v_palettes[24] = {
	RGB8(255,255,255), RGB8(207,207,207), RGB8(159,159,159), RGB8( 67, 67, 67)
	,
	RGB8(255,255,255), RGB8(110,120,120), RGB8( 63, 76, 76), RGB8( 44, 52, 52)
	,
	RGB8(255,255,255), RGB8(169, 86, 27), RGB8(128, 52, 18), RGB8( 86, 43, 23)
	,
	RGB8(255,255,255), RGB8(222,217,219), RGB8(164,141,146), RGB8(124,110,113)
	,
	RGB8(255,255,255), RGB8(134,234,219), RGB8( 28,142,125), RGB8( 20, 90, 79)
	,
	RGB8(255,255,255), RGB8(168,200,207), RGB8( 84,140,183), RGB8( 81,115,141)
	
};

const uint8_t drill_v_tiles[64] = {
	0x2b,0x15,0x15,0x0a,
	0x0b,0x05,0x05,0x02,
	0x03,0x01,0x01,0x00,
	0x00,0x00,0x00,0x00,
	
0xd4,0x7c,0xa8,0xf8,
	0xd0,0x70,0xa0,0xe0,
	0xc0,0x40,0x80,0x80,
	0x00,0x00,0x00,0x00,
	
0x15,0x2a,0x0b,0x15,
	0x05,0x0a,0x03,0x05,
	0x01,0x02,0x01,0x01,
	0x00,0x00,0x00,0x00,
	
0xa8,0xfc,0xd0,0x78,
	0xa0,0xf0,0xc0,0x60,
	0x80,0xc0,0x80,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t drill_v_metasprite0[] = {
	METASPR_ITEM(-4, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t drill_v_metasprite1[] = {
	METASPR_ITEM(-4, -8, 2, S_PAL(0)),
	METASPR_ITEM(0, 8, 3, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const drill_v_metasprites[2] = {
	drill_v_metasprite0, drill_v_metasprite1
};
