#pragma bank 1

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(drill_h)

const palette_color_t drill_h_palettes[24] = {
	RGB8(255,255,255), RGB8(207,207,207), RGB8(159,159,159), RGB8( 67, 67, 67)
	,
	RGB8(255,255,255), RGB8(110,120,120), RGB8( 63, 76, 76), RGB8( 44, 52, 52)
	,
	RGB8(255,255,255), RGB8(169, 86, 27), RGB8(128, 52, 18), RGB8( 86, 43, 23)
	,
	RGB8(255,255,255), RGB8(222,217,219), RGB8(164,141,146), RGB8(124,110,113)
	,
	RGB8(255,255,255), RGB8(134,234,219), RGB8( 28,142,125), RGB8( 20, 90, 79)
	,
	RGB8(255,255,255), RGB8(168,200,207), RGB8( 84,140,183), RGB8( 81,115,141)
	
};

const uint8_t drill_h_tiles[64] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x01,0x00,
	0x03,0x01,0x07,0x02,
	0x0f,0x05,0x1f,0x0a,
	
0x15,0x3f,0x0a,0x1f,
	0x05,0x0f,0x02,0x07,
	0x01,0x03,0x00,0x01,
	0x00,0x00,0x00,0x00,
	
0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x01,
	0x01,0x02,0x02,0x05,
	0x05,0x0a,0x0a,0x15,
	
0x3f,0x2a,0x15,0x1f,
	0x0a,0x0f,0x05,0x07,
	0x02,0x03,0x01,0x01,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t drill_h_metasprite0[] = {
	METASPR_ITEM(-8, -4, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 1, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t drill_h_metasprite1[] = {
	METASPR_ITEM(-8, -4, 2, S_PAL(0)),
	METASPR_ITEM(8, 0, 3, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const drill_h_metasprites[2] = {
	drill_h_metasprite0, drill_h_metasprite1
};
