//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_font_H
#define METASPRITE_font_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define font_TILE_ORIGIN 0
#define font_TILE_W 8
#define font_TILE_H 8
#define font_WIDTH 208
#define font_HEIGHT 24
#define font_TILE_COUNT 77

BANKREF_EXTERN(font)

extern const uint8_t font_tiles[1232];


#endif
