//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fuel_highlight_frame_H
#define METASPRITE_fuel_highlight_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fuel_highlight_frame_TILE_ORIGIN 0
#define fuel_highlight_frame_TILE_W 8
#define fuel_highlight_frame_TILE_H 8
#define fuel_highlight_frame_WIDTH 24
#define fuel_highlight_frame_HEIGHT 24
#define fuel_highlight_frame_TILE_COUNT 9

BANKREF_EXTERN(fuel_highlight_frame)

extern const uint8_t fuel_highlight_frame_tiles[144];


#endif
