//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fuel_frame_H
#define METASPRITE_fuel_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fuel_frame_TILE_ORIGIN 144
#define fuel_frame_TILE_W 8
#define fuel_frame_TILE_H 8
#define fuel_frame_WIDTH 160
#define fuel_frame_HEIGHT 144
#define fuel_frame_TILE_COUNT 76
#define fuel_frame_PALETTE_COUNT 1
#define fuel_frame_COLORS_PER_PALETTE 4
#define fuel_frame_TOTAL_COLORS 4
#define fuel_frame_MAP_ATTRIBUTES 0

BANKREF_EXTERN(fuel_frame)

extern const palette_color_t fuel_frame_palettes[4];
extern const uint8_t fuel_frame_tiles[1216];

extern const unsigned char fuel_frame_map[360];
#define fuel_frame_map_attributes fuel_frame_map

#endif
