//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fuel_frame_H
#define METASPRITE_fuel_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fuel_frame_TILE_ORIGIN 144
#define fuel_frame_TILE_W 8
#define fuel_frame_TILE_H 8
#define fuel_frame_WIDTH 160
#define fuel_frame_HEIGHT 144
#define fuel_frame_TILE_COUNT 60
#define fuel_frame_PALETTE_COUNT 7
#define fuel_frame_COLORS_PER_PALETTE 4
#define fuel_frame_TOTAL_COLORS 28
#define fuel_frame_MAP_ATTRIBUTES fuel_frame_map_attributes
#define fuel_frame_MAP_ATTRIBUTES_WIDTH 20
#define fuel_frame_MAP_ATTRIBUTES_HEIGHT 18
#define fuel_frame_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define fuel_frame_MAP_ATTRIBUTES_PACKED_HEIGHT 18

BANKREF_EXTERN(fuel_frame)

extern const palette_color_t fuel_frame_palettes[28];
extern const uint8_t fuel_frame_tiles[960];

extern const unsigned char fuel_frame_map[360];
extern const unsigned char fuel_frame_map_attributes[360];

#endif
