//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_game_over_H
#define METASPRITE_game_over_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_over_TILE_ORIGIN 55
#define game_over_TILE_W 8
#define game_over_TILE_H 8
#define game_over_WIDTH 56
#define game_over_HEIGHT 32
#define game_over_TILE_COUNT 28

BANKREF_EXTERN(game_over)

extern const uint8_t game_over_tiles[448];


#endif
