//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_game_over_skull_H
#define METASPRITE_game_over_skull_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define game_over_skull_TILE_ORIGIN 64
#define game_over_skull_TILE_W 8
#define game_over_skull_TILE_H 8
#define game_over_skull_WIDTH 32
#define game_over_skull_HEIGHT 48
#define game_over_skull_TILE_COUNT 27
#define game_over_skull_PIVOT_X 16
#define game_over_skull_PIVOT_Y 24
#define game_over_skull_PIVOT_W 32
#define game_over_skull_PIVOT_H 48
extern const metasprite_t* const game_over_skull_metasprites[4];

BANKREF_EXTERN(game_over_skull)

extern const uint8_t game_over_skull_tiles[432];

#endif
