//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_highlight_frame_H
#define METASPRITE_highlight_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define highlight_frame_TILE_ORIGIN 0
#define highlight_frame_TILE_W 8
#define highlight_frame_TILE_H 8
#define highlight_frame_WIDTH 24
#define highlight_frame_HEIGHT 24
#define highlight_frame_TILE_COUNT 32
#define highlight_frame_PALETTE_COUNT 1
#define highlight_frame_COLORS_PER_PALETTE 4
#define highlight_frame_TOTAL_COLORS 4
#define highlight_frame_PIVOT_X -8
#define highlight_frame_PIVOT_Y -16
#define highlight_frame_PIVOT_W 24
#define highlight_frame_PIVOT_H 24

BANKREF_EXTERN(highlight_frame)

extern const palette_color_t highlight_frame_palettes[4];
extern const uint8_t highlight_frame_tiles[512];

extern const metasprite_t* const highlight_frame_metasprites[4];

#endif
