//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_highlight_frame_bank3_H
#define METASPRITE_highlight_frame_bank3_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define highlight_frame_bank3_TILE_ORIGIN 0
#define highlight_frame_bank3_TILE_W 8
#define highlight_frame_bank3_TILE_H 8
#define highlight_frame_bank3_WIDTH 24
#define highlight_frame_bank3_HEIGHT 24
#define highlight_frame_bank3_TILE_COUNT 32
#define highlight_frame_bank3_PALETTE_COUNT 1
#define highlight_frame_bank3_COLORS_PER_PALETTE 4
#define highlight_frame_bank3_TOTAL_COLORS 4
#define highlight_frame_bank3_PIVOT_X -8
#define highlight_frame_bank3_PIVOT_Y -16
#define highlight_frame_bank3_PIVOT_W 24
#define highlight_frame_bank3_PIVOT_H 24
extern const metasprite_t* const highlight_frame_bank3_metasprites[4];

BANKREF_EXTERN(highlight_frame_bank3)

extern const palette_color_t highlight_frame_bank3_palettes[4];
extern const uint8_t highlight_frame_bank3_tiles[512];

#endif
