//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_highlight_frame_bank2_H
#define METASPRITE_highlight_frame_bank2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define highlight_frame_bank2_TILE_ORIGIN 0
#define highlight_frame_bank2_TILE_W 8
#define highlight_frame_bank2_TILE_H 8
#define highlight_frame_bank2_WIDTH 24
#define highlight_frame_bank2_HEIGHT 24
#define highlight_frame_bank2_TILE_COUNT 32
#define highlight_frame_bank2_PALETTE_COUNT 1
#define highlight_frame_bank2_COLORS_PER_PALETTE 4
#define highlight_frame_bank2_TOTAL_COLORS 4
#define highlight_frame_bank2_PIVOT_X -8
#define highlight_frame_bank2_PIVOT_Y -16
#define highlight_frame_bank2_PIVOT_W 24
#define highlight_frame_bank2_PIVOT_H 24
extern const metasprite_t* const highlight_frame_bank2_metasprites[4];

BANKREF_EXTERN(highlight_frame_bank2)

extern const palette_color_t highlight_frame_bank2_palettes[4];
extern const uint8_t highlight_frame_bank2_tiles[512];

#endif
