//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_main_menu_buttons_H
#define METASPRITE_main_menu_buttons_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define main_menu_buttons_TILE_ORIGIN 0
#define main_menu_buttons_TILE_W 8
#define main_menu_buttons_TILE_H 8
#define main_menu_buttons_WIDTH 56
#define main_menu_buttons_HEIGHT 24
#define main_menu_buttons_TILE_COUNT 21
#define main_menu_buttons_PIVOT_X 28
#define main_menu_buttons_PIVOT_Y 12
#define main_menu_buttons_PIVOT_W 56
#define main_menu_buttons_PIVOT_H 24

BANKREF_EXTERN(main_menu_buttons)

extern const uint8_t main_menu_buttons_tiles[336];

extern const metasprite_t* const main_menu_buttons_metasprites[1];

#endif
