//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_menubuttons_H
#define METASPRITE_menubuttons_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define menubuttons_TILE_ORIGIN 0
#define menubuttons_TILE_W 8
#define menubuttons_TILE_H 8
#define menubuttons_WIDTH 56
#define menubuttons_HEIGHT 24
#define menubuttons_TILE_COUNT 21
#define menubuttons_PIVOT_X 28
#define menubuttons_PIVOT_Y 12
#define menubuttons_PIVOT_W 56
#define menubuttons_PIVOT_H 24

BANKREF_EXTERN(menubuttons)

extern const uint8_t menubuttons_tiles[336];

extern const metasprite_t* const menubuttons_metasprites[1];

#endif
