//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_nav_H
#define METASPRITE_nav_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define nav_TILE_ORIGIN 128
#define nav_TILE_W 8
#define nav_TILE_H 8
#define nav_WIDTH 160
#define nav_HEIGHT 24
#define nav_TILE_COUNT 12
#define nav_PALETTE_COUNT 1
#define nav_COLORS_PER_PALETTE 4
#define nav_TOTAL_COLORS 4
#define nav_MAP_ATTRIBUTES 0

BANKREF_EXTERN(nav)

extern const palette_color_t nav_palettes[4];
extern const uint8_t nav_tiles[192];

extern const unsigned char nav_map[60];
#define nav_map_attributes nav_map

#endif
