//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_powerup_highlight_frame_H
#define METASPRITE_powerup_highlight_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define powerup_highlight_frame_TILE_ORIGIN 4
#define powerup_highlight_frame_TILE_W 8
#define powerup_highlight_frame_TILE_H 8
#define powerup_highlight_frame_WIDTH 48
#define powerup_highlight_frame_HEIGHT 24
#define powerup_highlight_frame_TILE_COUNT 20
#define powerup_highlight_frame_PIVOT_X -8
#define powerup_highlight_frame_PIVOT_Y -16
#define powerup_highlight_frame_PIVOT_W 48
#define powerup_highlight_frame_PIVOT_H 24

BANKREF_EXTERN(powerup_highlight_frame)

extern const uint8_t powerup_highlight_frame_tiles[320];

extern const metasprite_t* const powerup_highlight_frame_metasprites[4];

#endif
