//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_powerup_frame_H
#define METASPRITE_powerup_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define powerup_frame_TILE_ORIGIN 0
#define powerup_frame_TILE_W 8
#define powerup_frame_TILE_H 8
#define powerup_frame_WIDTH 160
#define powerup_frame_HEIGHT 144
#define powerup_frame_TILE_COUNT 60
#define powerup_frame_PALETTE_COUNT 7
#define powerup_frame_COLORS_PER_PALETTE 4
#define powerup_frame_TOTAL_COLORS 28
#define powerup_frame_MAP_ATTRIBUTES powerup_frame_map_attributes
#define powerup_frame_MAP_ATTRIBUTES_WIDTH 20
#define powerup_frame_MAP_ATTRIBUTES_HEIGHT 18
#define powerup_frame_MAP_ATTRIBUTES_PACKED_WIDTH 20
#define powerup_frame_MAP_ATTRIBUTES_PACKED_HEIGHT 18
extern const unsigned char powerup_frame_map[360];
extern const unsigned char powerup_frame_map_attributes[360];

BANKREF_EXTERN(powerup_frame)

extern const palette_color_t powerup_frame_palettes[28];
extern const uint8_t powerup_frame_tiles[960];

#endif
