//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_progressbar_H
#define METASPRITE_progressbar_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define progressbar_TILE_ORIGIN 0
#define progressbar_TILE_W 8
#define progressbar_TILE_H 8
#define progressbar_WIDTH 72
#define progressbar_HEIGHT 8
#define progressbar_TILE_COUNT 9

BANKREF_EXTERN(progressbar)

extern const uint8_t progressbar_tiles[144];


#endif
