//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_prop_H
#define METASPRITE_prop_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define prop_TILE_ORIGIN 19
#define prop_TILE_W 8
#define prop_TILE_H 8
#define prop_WIDTH 16
#define prop_HEIGHT 8
#define prop_TILE_COUNT 10
#define prop_PIVOT_X 8
#define prop_PIVOT_Y 4
#define prop_PIVOT_W 16
#define prop_PIVOT_H 8

BANKREF_EXTERN(prop)

extern const uint8_t prop_tiles[160];

extern const metasprite_t* const prop_metasprites[5];

#endif
