//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_rover_eye_H
#define METASPRITE_rover_eye_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define rover_eye_TILE_ORIGIN 0
#define rover_eye_TILE_W 8
#define rover_eye_TILE_H 8
#define rover_eye_WIDTH 8
#define rover_eye_HEIGHT 8
#define rover_eye_TILE_COUNT 1
#define rover_eye_PALETTE_COUNT 1
#define rover_eye_COLORS_PER_PALETTE 4
#define rover_eye_TOTAL_COLORS 4
#define rover_eye_PIVOT_X 8
#define rover_eye_PIVOT_Y 8
#define rover_eye_PIVOT_W 8
#define rover_eye_PIVOT_H 8
extern const metasprite_t* const rover_eye_metasprites[1];

BANKREF_EXTERN(rover_eye)

extern const palette_color_t rover_eye_palettes[4];
extern const uint8_t rover_eye_tiles[16];

#endif
