#pragma bank 1

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(rover_eye)

const palette_color_t rover_eye_palettes[4] = {
	RGB8(255,255,255), RGB8(255,255,255), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	
};

const uint8_t rover_eye_tiles[16] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x0c,0x00,0x10,0x00,
	0x00,0x00,0x00,0x00
	
};

const metasprite_t rover_eye_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const rover_eye_metasprites[1] = {
	rover_eye_metasprite0
};
