//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_rover_H
#define METASPRITE_rover_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define rover_TILE_ORIGIN 0
#define rover_TILE_W 8
#define rover_TILE_H 8
#define rover_WIDTH 16
#define rover_HEIGHT 64
#define rover_TILE_COUNT 16

BANKREF_EXTERN(rover)

extern const uint8_t rover_tiles[256];


#endif
