//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_shop_tiles_H
#define METASPRITE_shop_tiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shop_tiles_TILE_ORIGIN 0
#define shop_tiles_TILE_W 8
#define shop_tiles_TILE_H 8
#define shop_tiles_WIDTH 32
#define shop_tiles_HEIGHT 1152
#define shop_tiles_TILE_COUNT 576
#define shop_tiles_PALETTE_COUNT 1
#define shop_tiles_COLORS_PER_PALETTE 4
#define shop_tiles_TOTAL_COLORS 4

BANKREF_EXTERN(shop_tiles)

extern const palette_color_t shop_tiles_palettes[4];
extern const uint8_t shop_tiles_tiles[9216];


#endif
