//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_shop_highlight_frame_H
#define METASPRITE_shop_highlight_frame_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shop_highlight_frame_TILE_ORIGIN 0
#define shop_highlight_frame_TILE_W 8
#define shop_highlight_frame_TILE_H 8
#define shop_highlight_frame_WIDTH 32
#define shop_highlight_frame_HEIGHT 8
#define shop_highlight_frame_TILE_COUNT 4

BANKREF_EXTERN(shop_highlight_frame)

extern const uint8_t shop_highlight_frame_tiles[64];


#endif
