//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_shoptiles_H
#define METASPRITE_shoptiles_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shoptiles_TILE_ORIGIN 0
#define shoptiles_TILE_W 8
#define shoptiles_TILE_H 8
#define shoptiles_WIDTH 32
#define shoptiles_HEIGHT 1152
#define shoptiles_TILE_COUNT 576
#define shoptiles_PALETTE_COUNT 1
#define shoptiles_COLORS_PER_PALETTE 4
#define shoptiles_TOTAL_COLORS 4

BANKREF_EXTERN(shoptiles)

extern const palette_color_t shoptiles_palettes[4];
extern const uint8_t shoptiles_tiles[9216];


#endif
