//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splashscreen_GB_fix_H
#define METASPRITE_splashscreen_GB_fix_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splashscreen_GB_fix_TILE_ORIGIN 0
#define splashscreen_GB_fix_TILE_W 8
#define splashscreen_GB_fix_TILE_H 8
#define splashscreen_GB_fix_WIDTH 8
#define splashscreen_GB_fix_HEIGHT 8
#define splashscreen_GB_fix_TILE_COUNT 1

BANKREF_EXTERN(splashscreen_GB_fix)

extern const uint8_t splashscreen_GB_fix_tiles[16];

#endif
