//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_splashscreen_screen_H
#define METASPRITE_splashscreen_screen_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define splashscreen_screen_TILE_ORIGIN 0
#define splashscreen_screen_TILE_W 8
#define splashscreen_screen_TILE_H 8
#define splashscreen_screen_WIDTH 64
#define splashscreen_screen_HEIGHT 40
#define splashscreen_screen_TILE_COUNT 40
#define splashscreen_screen_PALETTE_COUNT 8
#define splashscreen_screen_COLORS_PER_PALETTE 4
#define splashscreen_screen_TOTAL_COLORS 32
#define splashscreen_screen_PIVOT_X 32
#define splashscreen_screen_PIVOT_Y 20
#define splashscreen_screen_PIVOT_W 64
#define splashscreen_screen_PIVOT_H 40

BANKREF_EXTERN(splashscreen_screen)

extern const palette_color_t splashscreen_screen_palettes[32];
extern const uint8_t splashscreen_screen_tiles[640];

extern const metasprite_t* const splashscreen_screen_metasprites[1];

#endif
