//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_stationupgrade_H
#define METASPRITE_stationupgrade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stationupgrade_TILE_ORIGIN 0
#define stationupgrade_TILE_W 8
#define stationupgrade_TILE_H 8
#define stationupgrade_WIDTH 72
#define stationupgrade_HEIGHT 40
#define stationupgrade_TILE_COUNT 28
#define stationupgrade_PALETTE_COUNT 1
#define stationupgrade_COLORS_PER_PALETTE 4
#define stationupgrade_TOTAL_COLORS 4

BANKREF_EXTERN(stationupgrade)

extern const palette_color_t stationupgrade_palettes[4];
extern const uint8_t stationupgrade_tiles[448];


#endif
