//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_sell_H
#define METASPRITE_station_sell_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_sell_TILE_ORIGIN 151
#define station_sell_TILE_W 8
#define station_sell_TILE_H 8
#define station_sell_WIDTH 64
#define station_sell_HEIGHT 40
#define station_sell_TILE_COUNT 33
#define station_sell_PALETTE_COUNT 8
#define station_sell_COLORS_PER_PALETTE 4
#define station_sell_TOTAL_COLORS 32
#define station_sell_MAP_ATTRIBUTES station_sell_map_attributes
#define station_sell_MAP_ATTRIBUTES_WIDTH 8
#define station_sell_MAP_ATTRIBUTES_HEIGHT 5
#define station_sell_MAP_ATTRIBUTES_PACKED_WIDTH 8
#define station_sell_MAP_ATTRIBUTES_PACKED_HEIGHT 5

BANKREF_EXTERN(station_sell)

extern const palette_color_t station_sell_palettes[32];
extern const uint8_t station_sell_tiles[528];

extern const unsigned char station_sell_map[40];
extern const unsigned char station_sell_map_attributes[40];

#endif
