//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_upgrade_H
#define METASPRITE_station_upgrade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_upgrade_TILE_ORIGIN 187
#define station_upgrade_TILE_W 8
#define station_upgrade_TILE_H 8
#define station_upgrade_WIDTH 72
#define station_upgrade_HEIGHT 40
#define station_upgrade_TILE_COUNT 44
#define station_upgrade_PALETTE_COUNT 8
#define station_upgrade_COLORS_PER_PALETTE 4
#define station_upgrade_TOTAL_COLORS 32
#define station_upgrade_MAP_ATTRIBUTES station_upgrade_map_attributes
#define station_upgrade_MAP_ATTRIBUTES_WIDTH 9
#define station_upgrade_MAP_ATTRIBUTES_HEIGHT 5
#define station_upgrade_MAP_ATTRIBUTES_PACKED_WIDTH 9
#define station_upgrade_MAP_ATTRIBUTES_PACKED_HEIGHT 5

BANKREF_EXTERN(station_upgrade)

extern const palette_color_t station_upgrade_palettes[32];
extern const uint8_t station_upgrade_tiles[704];

extern const unsigned char station_upgrade_map[45];
extern const unsigned char station_upgrade_map_attributes[45];

#endif
