//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_stationrepair_H
#define METASPRITE_stationrepair_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stationrepair_TILE_ORIGIN 0
#define stationrepair_TILE_W 8
#define stationrepair_TILE_H 8
#define stationrepair_WIDTH 72
#define stationrepair_HEIGHT 40
#define stationrepair_TILE_COUNT 42
#define stationrepair_PALETTE_COUNT 1
#define stationrepair_COLORS_PER_PALETTE 4
#define stationrepair_TOTAL_COLORS 4

BANKREF_EXTERN(stationrepair)

extern const palette_color_t stationrepair_palettes[4];
extern const uint8_t stationrepair_tiles[672];


#endif
