//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_stationrepair_H
#define METASPRITE_stationrepair_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stationrepair_TILE_ORIGIN 148
#define stationrepair_TILE_W 8
#define stationrepair_TILE_H 8
#define stationrepair_WIDTH 72
#define stationrepair_HEIGHT 40
#define stationrepair_TILE_COUNT 44
#define stationrepair_PALETTE_COUNT 1
#define stationrepair_COLORS_PER_PALETTE 4
#define stationrepair_TOTAL_COLORS 4
#define stationrepair_MAP_ATTRIBUTES 0

BANKREF_EXTERN(stationrepair)

extern const palette_color_t stationrepair_palettes[4];
extern const uint8_t stationrepair_tiles[704];

extern const unsigned char stationrepair_map[45];
#define stationrepair_map_attributes stationrepair_map

#endif
