//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_stationsell_H
#define METASPRITE_stationsell_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stationsell_TILE_ORIGIN 150
#define stationsell_TILE_W 8
#define stationsell_TILE_H 8
#define stationsell_WIDTH 64
#define stationsell_HEIGHT 40
#define stationsell_TILE_COUNT 35
#define stationsell_PALETTE_COUNT 1
#define stationsell_COLORS_PER_PALETTE 4
#define stationsell_TOTAL_COLORS 4
#define stationsell_MAP_ATTRIBUTES 0

BANKREF_EXTERN(stationsell)

extern const palette_color_t stationsell_palettes[4];
extern const uint8_t stationsell_tiles[560];

extern const unsigned char stationsell_map[40];
#define stationsell_map_attributes stationsell_map

#endif
