//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_upgrade_H
#define METASPRITE_station_upgrade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_upgrade_TILE_ORIGIN 187
#define station_upgrade_TILE_W 8
#define station_upgrade_TILE_H 8
#define station_upgrade_WIDTH 72
#define station_upgrade_HEIGHT 40
#define station_upgrade_TILE_COUNT 41
#define station_upgrade_PALETTE_COUNT 1
#define station_upgrade_COLORS_PER_PALETTE 4
#define station_upgrade_TOTAL_COLORS 4
#define station_upgrade_MAP_ATTRIBUTES 0

BANKREF_EXTERN(station_upgrade)

extern const palette_color_t station_upgrade_palettes[4];
extern const uint8_t station_upgrade_tiles[656];

extern const unsigned char station_upgrade_map[45];
#define station_upgrade_map_attributes station_upgrade_map

#endif
