//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_fuel_H
#define METASPRITE_station_fuel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_fuel_TILE_ORIGIN 128
#define station_fuel_TILE_W 8
#define station_fuel_TILE_H 8
#define station_fuel_WIDTH 56
#define station_fuel_HEIGHT 32
#define station_fuel_TILE_COUNT 22
#define station_fuel_PALETTE_COUNT 1
#define station_fuel_COLORS_PER_PALETTE 4
#define station_fuel_TOTAL_COLORS 4
#define station_fuel_MAP_ATTRIBUTES 0

BANKREF_EXTERN(station_fuel)

extern const palette_color_t station_fuel_palettes[4];
extern const uint8_t station_fuel_tiles[352];

extern const unsigned char station_fuel_map[28];
#define station_fuel_map_attributes station_fuel_map

#endif
