//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_stationupgrade_H
#define METASPRITE_stationupgrade_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define stationupgrade_TILE_ORIGIN 185
#define stationupgrade_TILE_W 8
#define stationupgrade_TILE_H 8
#define stationupgrade_WIDTH 72
#define stationupgrade_HEIGHT 40
#define stationupgrade_TILE_COUNT 41
#define stationupgrade_PALETTE_COUNT 1
#define stationupgrade_COLORS_PER_PALETTE 4
#define stationupgrade_TOTAL_COLORS 4
#define stationupgrade_MAP_ATTRIBUTES 0

BANKREF_EXTERN(stationupgrade)

extern const palette_color_t stationupgrade_palettes[4];
extern const uint8_t stationupgrade_tiles[656];

extern const unsigned char stationupgrade_map[45];
#define stationupgrade_map_attributes stationupgrade_map

#endif
