//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_H
#define METASPRITE_station_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_TILE_ORIGIN 64
#define station_TILE_W 8
#define station_TILE_H 8
#define station_WIDTH 88
#define station_HEIGHT 80
#define station_TILE_COUNT 110
#define station_PALETTE_COUNT 8
#define station_COLORS_PER_PALETTE 4
#define station_TOTAL_COLORS 32

BANKREF_EXTERN(station)

extern const palette_color_t station_palettes[32];
extern const uint8_t station_tiles[1760];


#endif
