//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_station_save_H
#define METASPRITE_station_save_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define station_save_TILE_ORIGIN 64
#define station_save_TILE_W 8
#define station_save_TILE_H 8
#define station_save_WIDTH 32
#define station_save_HEIGHT 40
#define station_save_TILE_COUNT 1
#define station_save_PALETTE_COUNT 8
#define station_save_COLORS_PER_PALETTE 4
#define station_save_TOTAL_COLORS 32
#define station_save_MAP_ATTRIBUTES station_save_map_attributes
#define station_save_MAP_ATTRIBUTES_WIDTH 4
#define station_save_MAP_ATTRIBUTES_HEIGHT 5
#define station_save_MAP_ATTRIBUTES_PACKED_WIDTH 4
#define station_save_MAP_ATTRIBUTES_PACKED_HEIGHT 5
extern const unsigned char station_save_map[20];
extern const unsigned char station_save_map_attributes[20];

BANKREF_EXTERN(station_save)

extern const uint8_t station_save_tiles[16];

#endif
