#pragma bank 1

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(station_save)

const palette_color_t station_save_palettes[32] = {
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	,
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	,
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	,
	RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	,
	RGB8(255,255,255), RGB8(185,136,134), RGB8(138, 59, 56), RGB8( 38, 38, 38)
	,
	RGB8(255,255,255), RGB8(185,136,134), RGB8(120, 90, 89), RGB8( 38, 38, 38)
	,
	RGB8(255,255,255), RGB8(255,255, 64), RGB8(120, 90, 89), RGB8( 38, 38, 38)
	,
	RGB8(255,255,255), RGB8(181,181,181), RGB8(120, 90, 89), RGB8( 38, 38, 38)
	
};

const uint8_t station_save_tiles[16] = {
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00,
	0x00,0x00,0x00,0x00
	};


const unsigned char station_save_map[20] = {
	0xae,0xae,0xae,0xa0,
	0xa1,0xa2,0xa3,0xa4,
	0xa5,0xa6,0xa7,0xa8,
	0xa9,0xaa,0xab,0xae,
	0xae,0xac,0xad,0xae,
};

const unsigned char station_save_map_attributes[20] = {
	0x04,0x04,0x04,0x04,
	0x07,0x07,0x07,0x07,
	0x07,0x07,0x07,0x07,
	0x07,0x07,0x07,0x04,
	0x04,0x07,0x07,0x04,
};
