//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tile_H
#define METASPRITE_tile_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tile_TILE_ORIGIN 0
#define tile_TILE_W 8
#define tile_TILE_H 8
#define tile_WIDTH 16
#define tile_HEIGHT 256
#define tile_TILE_COUNT 32

BANKREF_EXTERN(tile)

extern const uint8_t tile_tiles[512];


#endif
