//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_tracks_H
#define METASPRITE_tracks_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define tracks_TILE_ORIGIN 5
#define tracks_TILE_W 8
#define tracks_TILE_H 8
#define tracks_WIDTH 16
#define tracks_HEIGHT 8
#define tracks_TILE_COUNT 6
#define tracks_PALETTE_COUNT 1
#define tracks_COLORS_PER_PALETTE 4
#define tracks_TOTAL_COLORS 4
#define tracks_PIVOT_X 8
#define tracks_PIVOT_Y 4
#define tracks_PIVOT_W 16
#define tracks_PIVOT_H 8

BANKREF_EXTERN(tracks)

extern const palette_color_t tracks_palettes[4];
extern const uint8_t tracks_tiles[96];

extern const metasprite_t* const tracks_metasprites[3];

#endif
