#pragma bank 2

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(upgrade_tick)

const palette_color_t upgrade_tick_palettes[4] = {
	RGB8(255,255,255), RGB8(110,189, 23), RGB8( 72,106,  0), RGB8(  0,  0,  0)
	
};

const uint8_t upgrade_tick_tiles[16] = {
	0x3c,0x3c,0x7e,0x42,
	0xfd,0x83,0xfd,0x83,
	0xfd,0x83,0xf9,0x87,
	0x42,0x7e,0x3c,0x3c
	
};

const metasprite_t upgrade_tick_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const upgrade_tick_metasprites[1] = {
	upgrade_tick_metasprite0
};
