#pragma bank 2

//AUTOGENERATED FILE FROM png2asset

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(upgrade_tick)

const palette_color_t upgrade_tick_palettes[4] = {
	RGB8(255,255,255), RGB8(  0,255,124), RGB8(107, 41, 41), RGB8(225,255,  0)
	
};

const uint8_t upgrade_tick_tiles[16] = {
	0x02,0x01,0x05,0x02,
	0x0d,0x02,0xcb,0x04,
	0x3a,0xc4,0x96,0x68,
	0x4c,0x30,0x28,0x10
	
};

const metasprite_t upgrade_tick_metasprite0[] = {
	METASPR_ITEM(-4, -4, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t* const upgrade_tick_metasprites[1] = {
	upgrade_tick_metasprite0
};
