//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_upgrade_tick_H
#define METASPRITE_upgrade_tick_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define upgrade_tick_TILE_ORIGIN 32
#define upgrade_tick_TILE_W 8
#define upgrade_tick_TILE_H 8
#define upgrade_tick_WIDTH 8
#define upgrade_tick_HEIGHT 8
#define upgrade_tick_TILE_COUNT 1
#define upgrade_tick_PALETTE_COUNT 1
#define upgrade_tick_COLORS_PER_PALETTE 4
#define upgrade_tick_TOTAL_COLORS 4
#define upgrade_tick_PIVOT_X 4
#define upgrade_tick_PIVOT_Y 4
#define upgrade_tick_PIVOT_W 8
#define upgrade_tick_PIVOT_H 8
extern const metasprite_t* const upgrade_tick_metasprites[1];

BANKREF_EXTERN(upgrade_tick)

extern const palette_color_t upgrade_tick_palettes[4];
extern const uint8_t upgrade_tick_tiles[16];

#endif
