//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_warning_fuel_H
#define METASPRITE_warning_fuel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define warning_fuel_TILE_ORIGIN 55
#define warning_fuel_TILE_W 8
#define warning_fuel_TILE_H 8
#define warning_fuel_WIDTH 40
#define warning_fuel_HEIGHT 8
#define warning_fuel_TILE_COUNT 5

BANKREF_EXTERN(warning_fuel)

extern const uint8_t warning_fuel_tiles[80];


#endif
