//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_warningcargo_H
#define METASPRITE_warningcargo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define warningcargo_TILE_ORIGIN 48
#define warningcargo_TILE_W 8
#define warningcargo_TILE_H 8
#define warningcargo_WIDTH 56
#define warningcargo_HEIGHT 8
#define warningcargo_TILE_COUNT 7

BANKREF_EXTERN(warningcargo)

extern const uint8_t warningcargo_tiles[112];


#endif
