//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_warnings_H
#define METASPRITE_warnings_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define warnings_TILE_ORIGIN 48
#define warnings_TILE_W 8
#define warnings_TILE_H 8
#define warnings_WIDTH 96
#define warnings_HEIGHT 8
#define warnings_TILE_COUNT 12

BANKREF_EXTERN(warnings)

extern const uint8_t warnings_tiles[192];


#endif
