//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_warning_cargo_H
#define METASPRITE_warning_cargo_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define warning_cargo_TILE_ORIGIN 48
#define warning_cargo_TILE_W 8
#define warning_cargo_TILE_H 8
#define warning_cargo_WIDTH 56
#define warning_cargo_HEIGHT 8
#define warning_cargo_TILE_COUNT 7

BANKREF_EXTERN(warning_cargo)

extern const uint8_t warning_cargo_tiles[112];


#endif
