//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_warningfuel_H
#define METASPRITE_warningfuel_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define warningfuel_TILE_ORIGIN 55
#define warningfuel_TILE_W 8
#define warningfuel_TILE_H 8
#define warningfuel_WIDTH 40
#define warningfuel_HEIGHT 8
#define warningfuel_TILE_COUNT 5

BANKREF_EXTERN(warningfuel)

extern const uint8_t warningfuel_tiles[80];


#endif
